// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anwvjukiejkgkrubdpjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFud3ZqdWtpZWprZ2tydWJkcGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDU5NzgsImV4cCI6MjA2NTIyMTk3OH0.AW7GkX4Ckuk3oNK2tUwW80fUSJIBjz-9mf1FBzxfSnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);